# Generated by Django 3.0.9 on 2020-08-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
